---
- hosts: localhost
  connection: local
  become: true

  tasks:

  - name: copy dotfiles
    copy:
      src: files/bashrc
      dest: /home/vernon/.bashrc
      owner: vernon
      group: vernon

  - name: add ansible user
    user:
      name: gm-ansible
      system: yes

  - name: setup sudo for gm-ansible
    copy:
      src: files/sudoer_gm-ansible
      dest: /etc/sudoers.d/gm-ansible
      owner: root
      group: root
      mode: 0440

  - name: gm-ansible cron job
    cron:
      name: ansible auto-provision
      user: gm-ansible
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/vernonranis/ansible-desktop.git
